SELECT * FROM 
portfolio_project..COVID_DEATHS 
WHERE CONTINENT IS NOT NULL
ORDER BY 3,4

--SELECT * FROM 
--portfolio_project..COVID_VACCINATIONS 
--ORDER BY 3,4

SELECT *,DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='COVID_DEATHS'

SELECT LOCATION,DATE,TOTAL_CASES,NEW_CASES,TOTAL_DEATHS,POPULATION 
FROM portfolio_project..COVID_DEATHS
ORDER BY 1,2

--Looking at Total cases vs total deaths in usa

SELECT LOCATION,DATE,TOTAL_CASES,TOTAL_DEATHS,(CONVERT(FLOAT,TOTAL_DEATHS)/NULLIF(CONVERT(FLOAT,TOTAL_CASES),0))*100 AS DEATH_PERCENTAGE
FROM PORTFOLIO_PROJECT..COVID_DEATHS
WHERE LOCATION LIKE '%STATES%' AND continent IS NOT NULL AND total_deaths IS NOT NULL
ORDER BY 1,2

--LOOKING AT TOTAL CASES VS POPULATION IN USA

SELECT LOCATION,DATE,TOTAL_CASES,POPULATION,(TOTAL_CASES/POPULATION)*100 AS PERCENT_OF_POPULATION_INFECTED
FROM PORTFOLIO_PROJECT..COVID_DEATHS
WHERE LOCATION LIKE '%STATES%' AND  continent IS NOT NULL AND total_cases IS NOT NULL
ORDER BY 1,2

--LOOKING AT COUNTRIES WITH HIGHEST INFECTION RATE COMPARED TO POPULATION


SELECT LOCATION,POPULATION,MAX(TOTAL_CASES) AS HIGHEST_INFECTED_COUNT,
MAX((TOTAL_CASES/POPULATION))*100 AS PERCENT_OF_POPULATION_INFECTED
FROM PORTFOLIO_PROJECT..COVID_DEATHS
WHERE continent IS NOT NULL
GROUP BY LOCATION,POPULATION
ORDER BY PERCENT_OF_POPULATION_INFECTED DESC


--SHOWING COUNTRIES WITH HIGHEST DEATH COUNT PER POPULATION

SELECT LOCATION,POPULATION,MAX(TOTAL_DEATHS) AS TOTAL_DEATH_COUNT
FROM portfolio_project..COVID_DEATHS
WHERE continent IS NOT NULL
GROUP BY location,population
ORDER BY TOTAL_DEATH_COUNT DESC

--SHOWING CONTINENTS WITH HIGHEST DEATH COUNT 


SELECT continent,MAX(TOTAL_DEATHS) AS TOTAL_DEATH_COUNT
FROM portfolio_project..COVID_DEATHS
WHERE continent IS NOT NULL
GROUP BY continent
ORDER BY TOTAL_DEATH_COUNT DESC


--WORLDWIDE TOTAL CASES,TOTAL DEATHS AND DEATH PERCENTAGE PER DAY

SELECT DATE,SUM(NEW_CASES) AS TOTAL_CASES_GLOBALLY,
SUM(NEW_DEATHS) AS TOTAL_DEATHS_GLOBALLY,
(SUM(NEW_DEATHS)/NULLIF(SUM(NEW_CASES),0))*100 AS DEATH_PERCENT_GLOBALLY FROM portfolio_project..COVID_DEATHS
WHERE CONTINENT IS NOT NULL
GROUP BY DATE
ORDER BY DEATH_PERCENT_GLOBALLY DESC

--JOINING DEATHS AND VACCINATED TABLES

SELECT * FROM portfolio_project..COVID_DEATHS DEA
JOIN
portfolio_project..COVID_VACCINATIONS VAC
ON
DEA.location=VAC.location

--LOOKING AT TOTAL POPULATION VS VACCINATED

SELECT DEA.continent,DEA.date,DEA.population,VAC.new_vaccinations ,
SUM(CAST(VAC.NEW_VACCINATIONS AS bigint)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION,DEA.DATE) AS ROLLING_PEOPLE_VACCINATED
FROM portfolio_project..COVID_DEATHS DEA
JOIN
portfolio_project..COVID_VACCINATIONS VAC
ON
DEA.location=VAC.location 
AND 
DEA.date=DEA.date
WHERE DEA.continent IS NOT NULL
ORDER BY 2,3

---USE CTE
WITH POPULATION_VS_VACCINATED(CONTINENT,DATE,POPULATION,NEW_VACCINATIONS,ROLLING_PEOPLE_VACCINATED)
AS
(
SELECT DEA.continent,DEA.date,DEA.population,VAC.new_vaccinations ,
SUM(CAST(VAC.NEW_VACCINATIONS AS bigint)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION,DEA.DATE) AS ROLLING_PEOPLE_VACCINATED
FROM portfolio_project..COVID_DEATHS DEA
JOIN
portfolio_project..COVID_VACCINATIONS VAC
ON
DEA.location=VAC.location 
AND 
DEA.date=DEA.date
WHERE DEA.continent IS NOT NULL
--ORDER BY 2,3
)

SELECT *,(ROLLING_PEOPLE_VACCINATED/POPULATION)*100 FROM POPULATION_VS_VACCINATED

--TEMP TABLE
DROP TABLE IF EXISTS #PERCENT_POPULATION_VACCINATED
CREATE TABLE #PERCENT_POPULATION_VACCINATED
(
continent NVARCHAR(255),
DATE DATETIME,
POPULATION FLOAT,
new_vaccinations NVARCHAR(255),
ROLLING_PEOPLE_VACCINATED NUMERIC
)
INSERT INTO #PERCENT_POPULATION_VACCINATED
SELECT DEA.continent,DEA.date,DEA.population,VAC.new_vaccinations ,
SUM(CAST(VAC.NEW_VACCINATIONS AS bigint)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION,DEA.DATE) AS ROLLING_PEOPLE_VACCINATED
FROM portfolio_project..COVID_DEATHS DEA
JOIN
portfolio_project..COVID_VACCINATIONS VAC
ON
DEA.location=VAC.location 
AND 
DEA.date=DEA.date
--WHERE DEA.continent IS NOT NULL
--ORDER BY 2,3

SELECT *,(ROLLING_PEOPLE_VACCINATED/POPULATION)*100 FROM #PERCENT_POPULATION_VACCINATED





--CREATE VIEW TO STORE DATA FOR LATER VISUALIZATION

CREATE VIEW PERCENT_POPULATION_VACCINATED AS

SELECT DEA.continent,DEA.date,DEA.population,VAC.new_vaccinations ,
SUM(CAST(VAC.NEW_VACCINATIONS AS bigint)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION,DEA.DATE) AS ROLLING_PEOPLE_VACCINATED
FROM portfolio_project..COVID_DEATHS DEA
JOIN
portfolio_project..COVID_VACCINATIONS VAC
ON
DEA.location=VAC.location 
AND 
DEA.date=DEA.date
WHERE DEA.continent IS NOT NULL
--ORDER BY 2,3

SELECT * FROM PERCENT_POPULATION_VACCINATED